#!/bin/bash

u() {
    printf '\e[4m%s\e[0m' "$*"
}

mysql_shell() {
    docker run --rm -it \
        --network "$docker_network" \
        "$db_name" \
        mysql -u "$1" -p"$1" -h "$docker_name" "$1" -P "$internal_port"
}

postgres_shell() {
    docker run --rm -it \
        --network "$docker_network" \
        "$db_name" \
        bash -c "
            echo '$docker_name:$internal_port:$1:$1:$1' > ~/.pgpass;
            chmod 600 ~/.pgpass;
            psql -U $1 -h $docker_name -p $internal_port $1;
        "
}

get_current_port() {
    docker inspect "$1" | jq -r '.[] | .NetworkSettings.Ports["'$internal_port'/tcp"][0].HostPort'
}

port_active() (
    read -t 1 -n 1 _ < /dev/tcp/127.0.0.1/"$1"
    error=$?

    if (( error == 0 || error > 128 )); then
        exit 0
    else
        exit 1
    fi
) &> /dev/null

cmd_name=$( basename "$0" )
declare -A trade_names=(
    [mysql]=MySQL
    [postgres]=PostgreSQL
)

declare -A port_numbers=(
    [mysql]=3306
    [postgres]=5432
)

db_name=${cmd_name##*-}
db_trade_name=${trade_names[$db_name]}
prefix=$db_name-
identifier=
force=
only_kill=
list=
shell=
wait=

if [[ -z $db_trade_name ]]; then
    echo "error: unknown DB type '$db_name'" >&2
    exit 1
fi

for arg in "$@"; do
    case $arg in
        -f | --force )
            force=1
            ;;
        -l | --list )
            # TODO: implement
            list=1
            ;;
        --shell )
            shell=1
            ;;
        --wait )
            wait=1
            ;;
        -k | --kill )
            only_kill=1
            ;;
        -h | --help )
            cat <<HELP
USAGE
    $( basename "$0" ) [-f|--force] [--shell] [--wait] $( u 'IDENTIFIER' )
    $( basename "$0" ) [-k|--kill] $( u 'IDENTIFIER' )
    $( basename "$0" ) [-h|--help]

DESCRIPTION
    Creates an emphemeral $db_trade_name database with
    Docker using $( u "IDENTIFIER" ) as the root password, main
    username, their password, and also the primary
    database name. $( u 'IDENTIFIER' ) can't start or end
    with dashes, but overall can include alphanumberic
    characters, underscores, and dashes.
HELP
            exit 0
            ;;
        -* )
            echo "error: invalid argument '$arg'" >&2
            exit 1
            ;;
        * )
            identifier=$arg
            ;;
    esac
done

declare -i internal_port=${port_numbers[$db_name]}
declare -i host_port=$internal_port
while port_active "$host_port"; do
    host_port+=1
done

if [[ -z $identifier ]]; then
    echo "error: missing required paramete IDENTIFIER" >&2
    exit 1
elif [[ ! $identifier =~ ^[a-z0-9_]+([a-z0-9_-]+[a-z0-9_]|[a-z0-9_]*)$ ]]; then
    echo "error: identifier contains illegal characters" >&2
    exit 1
fi

docker_name=$prefix$identifier
docker_network=ephemeral-tmp-db-network
docker network create "$docker_network" &> /dev/null

if docker inspect "$docker_name" &> /dev/null; then
    if [[ $only_kill || $force ]]; then
        if docker rm -f "$docker_name" &> /dev/null; then
            echo "Removed existing container successfully"

            [[ $only_kill ]] && exit
        else
            echo "Failed to remove existing container '$docker_name'" >&2
            exit 1
        fi
    elif [[ $shell || $wait ]]; then
        wait_reason=shell
        [[ $wait ]] && wait_reason=wait

        current_port=$( get_current_port "$docker_name" )

        if ! port_active "$current_port"; then
            echo "$wait_reason: waiting for database to reach a ready state..."

            # Wait for the server to get ready
            while ! port_active "$current_port"; do
                sleep 1
            done
        fi

        if [[ $shell ]]; then
            echo "Connecting to '$docker_name':$current_port..."
            "${db_name}_shell" "$identifier"
        else
            echo "wait: database ready"
        fi

        exit
    else
        echo "Container '$docker_name' already exists... abort" >&2
        exit 1
    fi
elif [[ $only_kill ]]; then
    echo "No container '$docker_name' to kill"
    exit
fi

declare -A mysql_env_vars=(
    [root_pass]=MYSQL_ROOT_PASSWORD
    [user]=MYSQL_USER
    [pass]=MYSQL_PASSWORD
    [db]=MYSQL_DATABASE
)

declare -A postgres_env_vars=(
    [root_pass]=__NO_ROOT_PASSWORD_TO_SET
    [user]=POSTGRES_USER
    [pass]=POSTGRES_PASSWORD
    [db]=POSTGRES_DB
)

declare -n env_vars=${db_name}_env_vars

docker run --rm -d \
    -e ${env_vars[root_pass]}="$identifier" \
    -e ${env_vars[user]}="$identifier" \
    -e ${env_vars[pass]}="$identifier" \
    -e ${env_vars[db]}="$identifier" \
    -p $host_port:$internal_port \
    --network "$docker_network" \
    --name "$docker_name" \
    "$db_name" && {
    echo "Created new ephemeral $db_trade_name database '$docker_name':$host_port successfully"

    if [[ $shell || $wait ]]; then
        wait_reason=shell
        [[ $wait ]] && wait_reason=wait
        echo "$wait_reason: waiting for database to reach a ready state..."

        # Wait for the server to get ready
        while ! port_active "$host_port"; do
            sleep 1
        done

        if [[ $shell ]]; then
            "${db_name}_shell" "$identifier"
        else
            echo "wait: database ready"
        fi
    fi

    exit
}

echo "Failed to create $db_trade_name database '$docker_name':$host_port..." >&2
exit 1
